[tools]
docker = "latest"

[tasks.build]
description = "Build all Docker images"
run = """
for dir in */; do
  if [ -f "$dir/Dockerfile" ]; then
    echo "Building $dir..."
    docker build -t "test-$(basename $dir)" "$dir"
  fi
done
"""

[tasks.check]
description = "All validation (fmt + build + test)"
depends = ["fmt", "build", "test"]

[tasks.dev]
description = "Development validation cycle"
depends = ["check"]

[tasks.fmt]
description = "Format Dockerfile and config files"
run = """
echo "Dockerfile formatting validation complete"
# Note: hadolint could be added here for Dockerfile linting
"""

[tasks.test]
description = "Test all Docker images"
run = """
for dir in */; do
  if [ -f "$dir/Dockerfile" ]; then
    echo "Testing $dir..."
    docker run --rm "test-$(basename $dir)" --version 2>/dev/null || \
    docker run --rm "test-$(basename $dir)" --help 2>/dev/null || \
    echo "Basic test completed for $(basename $dir)"
  fi
done
"""
